/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jstacs_utils_UserTime */

#ifndef _Included_de_jstacs_utils_UserTime
#define _Included_de_jstacs_utils_UserTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jstacs_utils_UserTime
 * Method:    getUserTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_jstacs_utils_UserTime_getUserTime
  (JNIEnv *, jobject);

/*
 * Class:     de_jstacs_utils_UserTime
 * Method:    getTicks
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_jstacs_utils_UserTime_getTicks
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
